### ISSUE TITLE
the extention did not support object and string chosen from list of option parameters

### ISSUE THREAD

**Issue by kegbaria** [freesonlee/azure-devops-utilities#4]
- name: VSTS_RUNNER_FPGA_MODULE
    displayName: FPGA MODULE 
    type: string
    default: 'N/A'
    values:
      - N/A
      - mtv_ww50.0.LC_100M
      - mtv_ww49.0.LC_100M
      - mtv_ww48.1
      - gbr_pd_xtor.ww04.4a.buf128 
      - gbr_pd_xtor.ww04.4

  - name: VSTS_TESTS
    displayName: test to run 
    type: object
    default:
      Test: {Name: Test ,nvm: blabla}
      Test1: BAR

issue description : 
object type (like : VSTS_TESTS ) did not even show in the extension 
and the string from list , even it shown by the extension   and allow me to choice but the value did not pass when i trigger the build or save it

**Comment by freesonlee** [comment]
object type is not supported to show in the variable list. 
What would like to have for object type parameter? An editor input that supports JSON?
If that doesn't take time to implement, I would like to support that.

**Comment by kegbaria** [comment]
1. yes i would like to have the option to see and to set object format like in normal pipeline editor (same format) when we trigger pipeline , (there is no reason to convert the json to an editor on the editor only need the option to set it )

2. regarding the list of string (VSTS_RUNNER_FPGA_MODULE) ,  your extension shown it but after select and trigger what i selected not passed to the build 

![MTVE](https://github.com/freesonlee/azure-devops-utilities/assets/128597396/3c93dabf-902e-41f7-b9c1-92ffa14649fb)

let me know if something not clear and thanks

**Comment by freesonlee** [comment]
Make sense. 
I have actually made some change yesterday and updated the extension. It should :
1. Let you save VSTS_RUNNER_FPGA_MODULE.
2. Also see the object type parameter, however it doesn't have syntax highlight (such as ace editor). And I am now adjusting the width of the text boxes.

**Comment by freesonlee** [comment]
Just updated extension. Try reload and see if that fixes everything.

**Comment by kegbaria** [comment]
Thanks , look great 
last thing and it's not urgent : look like the width of text element combo box \ textbox is fixed , can you make it dynamic width based align to the windows\container width 

![MTVE2](https://github.com/freesonlee/azure-devops-utilities/assets/128597396/5435e40f-87cc-4155-bc50-07da60117906)

**Comment by freesonlee** [comment]
Understand. 
Instead of auto resizing, I would like to support multiple line for them. Like variables, you can keep line breaks or  replace line breaks with space.

**Comment by freesonlee** [comment]
Closing the issue.
Since this is not built using `azure-devops-ui`, I would not spent too much time on UI, until maybe one day I re-write UI with that library.

**Comment by kegbaria** [comment]
you already provieded a great support Thanks

________________________________
